#!/bin/sh
# Ingress --HTTP/1.1--> Envoy --HTTP/1.1--> nginx --HTTP/1.1--> java-demo
# While below command is running, restart the nginx deployment:
#   You SHOULD NOT see any 503 errors generated by Envoy, because nginx's graceful shutdown
#   upon receiving SIGQUIT (default container image signal) will set `Connection: close` on
#   responses for requests from Envoy so that those connections will terminate cleanly.
#   And even in the case of connections not seeing any requests after graceful shutdown starts
#   there is the nginx property keepalive_min_timeout which we will set to at least the client's
#   keep-alive timeout. If clients do not send any requests for a connection for this duration
#   the clients will themselves close the connection due to timeout and there will be no problem.
# Alternatively, restart the java-demo deployment:
#   You SHOULD see 502 errors.
#   This is because the Tomcat web server will only wait for currently active
#   HTTP requests to finish and then shut down immediately, including closing any
#   keep-alive connections. This closing of keep-alive connections races with
#   requests a client (Nginx in this case) is just about to send over it.
#   This then results in TCP RST packets emitted by the backend server (Tomcat).
LOAD_BALANCER_IP="$(kubectl get services -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
oha -c 100 -z 10m -m POST -d '{}' -H "Content-Type: application/json" -H "Host: envoy" "http://$LOAD_BALANCER_IP/nginx/java-demo/sleep?min=50&max=200"

