FROM golang:1.26.0-alpine3.23 AS builder
WORKDIR /build
ADD main.go .
RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags '-s -w -extldflags "-static" -buildid=' \
    -o app main.go
FROM scratch
USER 1001:1001
COPY --chown=1001:1001 --from=builder /build/app /app
CMD ["/app"]

